export const DEVELOPMENT = 'development'
export const PRODUCTION = 'production'
export const TEST = 'test'
export const SEQUELIZE = 'SEQUELIZE'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const FEEDBACK_REPOSITORY = 'FEEDBACK_REPOSITORY'